# Generated by Django 2.2.7 on 2019-12-06 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('summary', models.CharField(blank=True, max_length=10000, null=True)),
                ('teacher', models.CharField(max_length=100)),
                ('method', models.CharField(max_length=100)),
                ('characteristic', models.CharField(blank=True, max_length=100, null=True)),
                ('if_provide_lab', models.BooleanField(default=True)),
                ('detail', models.CharField(max_length=10000)),
            ],
        ),
        migrations.CreateModel(
            name='StudentsDB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='学员姓名')),
                ('mail', models.EmailField(max_length=100, unique=True, verbose_name='学员邮件')),
                ('edit_date', models.DateField(auto_now=True, verbose_name='修改时间')),
            ],
        ),
    ]
