# Generated by Django 2.2.7 on 2019-12-07 09:14

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app_001', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OPRS_DB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名')),
                ('device_sn', models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='SN must be ....', regex='^\\S*$')])),
                ('device_ip', models.GenericIPAddressField(unique=True, verbose_name='设备管理ip')),
                ('mail', models.EmailField(max_length=100, unique=True, verbose_name='厂家联系邮件')),
                ('device_type', models.CharField(choices=[('router', '路由器'), ('switch', '交换机')], max_length=5)),
                ('device_op', models.BooleanField(choices=[(True, '已纳管'), (False, '未纳管')], default=False)),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
                ('update_date', models.DateTimeField(auto_now_add=True, verbose_name='修改时间')),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='StudentsDB',
        ),
    ]
