# Generated by Django 2.2.7 on 2019-12-07 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app_001', '0003_oprs_db_tips'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oprs_db',
            name='device_type',
            field=models.CharField(choices=[('router', '路由器'), ('switch', '交换机')], max_length=10),
        ),
    ]
