# Generated by Django 2.2.7 on 2019-12-11 08:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Django_app_001', '0006_auto_20191207_1508'),
    ]

    operations = [
        migrations.CreateModel(
            name='CPU_memory_utli',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_name', models.CharField(max_length=100, verbose_name='设备名')),
                ('device_ip', models.GenericIPAddressField(unique=True, verbose_name='设备管理ip')),
                ('cpu_utli', models.IntegerField(verbose_name='CPU利用率')),
                ('memory_utli', models.IntegerField(verbose_name='memory利用率')),
                ('create_date', models.DateTimeField(auto_now=True, verbose_name='采集时间')),
            ],
        ),
        migrations.AlterField(
            model_name='oprs_db',
            name='device_sn',
            field=models.CharField(max_length=11, unique=True, validators=[django.core.validators.RegexValidator(message='SN must be ....', regex='^\\S*$')]),
        ),
    ]
